name: OpenAI API Call
on:
  push:
    branches: [ main, master ]
jobs:
  openai_call:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get committed code
      run: |
        git diff-tree --no-commit-id --name-only -r $(git rev-parse HEAD) > committed_files.txt

    - name: Send code to OpenAI API
      run: |
        COMMITTED_CODE=""
        while read file; do
          COMMITTED_CODE+=$(cat $file | tr '\n' ' ')
        done < committed_files.txt

        RESPONSE=$(curl --location 'https://api.openai.com/v1/chat/completions' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: Bearer ${{ secrets.OPENAI_API_KEY}}' \
        --data '{
            "model": "gpt-3.5-turbo",
            "messages": [
              {
                "role": "system",
                "content": "The user is going to send a piece of code, if the code it'\''s bugged can you fix and return in this format: Bugs were found, here is the solution:\n {fixed code}? If it'\''s not bugged can you just send: No bugs were founded"
              },
              {
                "role": "user",
                "content": "'"${COMMITTED_CODE}"'"
              }
            ]
        }')

        echo $RESPONSE > response.txt

    - name: Print OpenAI API response
      run: cat response.txt
